global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: odoo-16
  tag: latest

config:
  TZ: ""
  ODOO_DB_HOST: ""
    
secrets:
  DOO_DB_USER: ""
  ODOO_DB_PASSWORD: ""

service:
  type: ClusterIP
  port: 8069

autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}
