apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  TZ: "{{ .Values.global.TZ }}"
  HOST: "{{ .Values.config.ODOO_DB_HOST }}"
  NAME: "{{ .Values.config.ODOO_DB_NAME }}"
  DB_FILTER: "{{ .Values.config.ODOO_DB_FILTER }}"
  